version: "3.8"

services:
  exchange-mongodb:
    image: mongo
    container_name: exchange-mongodb
    env_file:
        - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_PASSWORD}
    ports:
      -27017:27017
      